# Global application options.
# Attachment directory, markdown notes file, output file name values here can be
# overridden on the command line.
AppOptions:
    OutputFileName: "Bleh.pdf"
    AttachmentsDirectory: "TBD"
    MarkdownNotesFileName: ""
    InputData:
        IagoSampleSet: 
            DataLocation: "axdadf"
        AzurePerfSampleSet:
            DataLocation: ""
        SomeOtherSampleSet:
            DataLocation: "something of meaning"

IagoSample:
# fields to be ignored when analysing individual stats
    FieldsToIgnore:
        - "count"
        - "200"

AzureMetricsSampleSet:
    Fields:
        - "CpuTime"
        - "AverageMemoryWorkingSet"
        - "MemoryWorkingSet"
        
IagoSampleSet:
# should fields ignored for individual statistics also be ignored when analyzed as a set?
    IncludeStasticsIgnoredFields: "false" 
# fields to be ignored when analysing the complete stat set
    FieldsToIgnore:
        - "count"
        - "200"

AzureMetricsSampleSetAnalysis:
    Graphs:
        
IisSampleSetAnalysis:
    Graphs:

IagoSampleSetAnalysis:
    Graphs:
        - { Title: "Combined Request Latencies",
            Statistics: ["client/request_latency_ms_minimum", "client/request_latency_ms_average", "client/request_latency_ms_maximum"],
            Description: "",
            IncludeAverage: "true",
            IncludeStdDeviation: "true"
          }
        - { Title: "Average Request Lantency (ms)",
            Statistics: "client/request_latency_ms_average",
            Description: "",
            IncludeAverage: "true",
            IncludeStdDeviation: "true"
          }
        - { Title: "Maximum Request Latency (ms)",
            Statistics: "client/request_latency_ms_maximum",
            Description: "",
            IncludeAverage: "true",
            IncludeStdDeviation: "true"
          }
        - { Title: "Minimum Request Latency",
            Statistics: "client/request_latency_ms_minimum",
            Description: "",
            IncludeAverage: "true",
            IncludeStdDeviation: "true"
          }
        - { Title: "Minimum Request Latency - no std dev",
            Statistics: "client/request_latency_ms_minimum",
            Description: "",
            IncludeAverage: "true",
            IncludeStdDeviation: "false"
          }
        - { Title: "Minimum Request Latency - no average",
            Statistics: "client/request_latency_ms_minimum",
            Description: "",
            IncludeAverage: "false",
            IncludeStdDeviation: "false "
          }
