# Global application options.
# Attachment directory, markdown notes file, output file name values here can be
# overridden on the command line.
AppOptions:
    OutputFileName: "Bleh"
    AttachmentsDirectory: "TBD"
    MarkdownNotesFileName: ""
    GraphType: "OxyPlot"
    InputData:
        IagoStatSet: 
            DataLocation: "axdadf"
        AzurePerfStatSet:
            DataLocation: ""
        SomeOtherStatSet:
            DataLocation: "something of meaning"

IagoStatistics:
# fields to be ignored when analysing individual stats
    FieldsToIgnore:
        - "count"
        - "200"

AzureMetricsStatisticsSet:
    Fields:
        - "CpuTime"
        - "AverageMemoryWorkingSet"
        - "MemoryWorkingSet"
        
IagoStatisticsSet:
# should fields ignored for individual statistics also be ignored when analyzed as a set?
    IncludeStasticsIgnoredFields: "false" 
# fields to be ignored when analysing the complete stat set
    FieldsToIgnore:
        - "count"
        - "200"

IagoStatSetAnalysis:
    StatsToLineGraph:
        - { Title: "Average Request Lantency (ms)",
            Statistic: "client/request_latency_ms_average",
            Description: "",
            IncludeAverage: "true",
            IncludeStdDeviation: "true"
          }
        - { Title: "Maximum Request Latency (ms)",
            Statistic: "client/request_latency_ms_maximum",
            Description: "",
            IncludeAverage: "true",
            IncludeStdDeviation: "true"
          }
        - { Title: "Minimum Request Latency",
            Statistic: "client/request_latency_ms_minimum",
            Description: "",
            IncludeAverage: "true",
            IncludeStdDeviation: "true"
          }