# Global application options.
# Attachment directory, markdown notes file, output file name values here can be
# overridden on the command line.
AppConfiguration:
    DataProcessingAssemblies:
        - "NorwegianBlue.Integration.Azure"
        - "NorwegianBlue.Integration.IIS"
        - "NorwegianBlue.Integration.Iago"
        - "NorwegianBlue.AnalyzableExperiment"
        - "NorwegianBlue.CommonAnalyzers"
    OutputFileName: "Bleh.pdf"
    AttachmentsDirectory: "TBD"
    MarkdownNotesFileName: ""
    InputData:
        IagoSampleSet: 
            DataLocation: "axdadf"
        AzurePerfSampleSet:
            DataLocation: ""
        SomeOtherSampleSet:
            DataLocation: "something of meaning"

Experiment:
    DataSets:
        - { 
            Factory: "IagoSampleSet",
            CustomConfig: ,
            SetAnalyzers: ["asdf", "asdfadf"],
            StatAnalyzers:
          }
        - { 
            Factory: "AzureMetricsSampleSet",
            CustomConfig: ,
            SetAnalyzers: ,
            StatAnalyzers:
          }
        - { 
            Factory: "IisSampleSet",
            CustomConfig: ,
            SetAnalyzers: ,
            StatAnalyzers:
          }
    # will be run on all data sets, before their specific analyzers
    CommonDataSetAnalysis:
        SetAnalyzers:
        StatAnalyzers:
    ExperimentAnalyzers:
    

IagoSample:
# fields to be ignored when analysing individual stats
    FieldsToIgnore:
        - "count"
        - "200"

AzureMetricsSample:
    FieldsToIgnore:
        - "zzzz"

AzureMetricsSampleSet:
    Fields:
        - "CpuTime"
        - "AverageMemoryWorkingSet"
        - "MemoryWorkingSet"
        
IagoSampleSet:
# fields to be ignored when analysing the complete stat set
    FieldsToIgnore:
        - "count"
        - "200"

AzureMetricsSampleSetAnalysis:
    Graphs:
        - { Title: "CPU Time",
            Statistics: "CPU",
            Description: "",
            IncludeAverage: "true",
            IncludeStdDeviation: "true"
          }
        - { Title: "Average Memory Working Set",
            Statistics: "AverageMemoryWorkingSet",
            Description: "",
            IncludeAverage: "true",
            IncludeStdDeviation: "true"
          }
        - { Title: "Memory Working Set",
            Statistics: "MemoryWorkingSet",
            Description: "",
            IncludeAverage: "true",
            IncludeStdDeviation: "true"
          }
        
IisSampleSetAnalysis:
    Graphs:

IagoSampleSetAnalysis:
    Graphs:
        - { Title: "Combined Request Latencies",
            Statistics: ["client/request_latency_ms_minimum", "client/request_latency_ms_average", "client/request_latency_ms_maximum"],
            Description: "",
            IncludeAverage: "true",
            IncludeStdDeviation: "true"
          }
        - { Title: "Average Request Lantency (ms)",
            Statistics: "client/request_latency_ms_average",
            Description: "",
            IncludeAverage: "true",
            IncludeStdDeviation: "true"
          }
        - { Title: "Maximum Request Latency (ms)",
            Statistics: "client/request_latency_ms_maximum",
            Description: "",
            IncludeAverage: "true",
            IncludeStdDeviation: "true"
          }
        - { Title: "Minimum Request Latency",
            Statistics: "client/request_latency_ms_minimum",
            Description: "",
            IncludeAverage: "true",
            IncludeStdDeviation: "true"
          }
        - { Title: "Minimum Request Latency - no std dev",
            Statistics: "client/request_latency_ms_minimum",
            Description: "",
            IncludeAverage: "true",
            IncludeStdDeviation: "false"
          }
        - { Title: "Minimum Request Latency - no average",
            Statistics: "client/request_latency_ms_minimum",
            Description: "",
            IncludeAverage: "false",
            IncludeStdDeviation: "false "
          }
