AppOptions:
    OutputFileName: "Bleh"
    AttachmentsDirectory: "TBD"
    MarkdownNotesFileName: ""
    GraphType: "OxyPlot"

IagoStatistics:
    IagoStatisticsSet : "C:\\tmp\\parrot-server-stats.log"
    Filters:
        Name: "one"
        Asdf: "two"

AzureMetricsStatisticsSet:
    Fields:
        - "CpuTime"
        - "AverageMemoryWorkingSet"
        - "MemoryWorkingSet"

IISStatistics:
    SubKey: "asdf"
    AppName: "asdf"