AppOptions:
    OutputFileName: "Bleh"
    AttachmentsDirectory: "TBD"
    MarkdownNotesFileName: "TBD"
    InputFileNames:
        IagoStatisticsSet : "C:\\tmp\\parrot-server-stats.log"
        IISStatsSet : "TBD"
        AzurePerfStatsSet : "TBD"
    GraphType: "OxyPlot"

Rules:
  - Type: "IagoStatistics"
    Filters:
        - "one"
        - "two"
        - "three"
    Settings:
        Param : "Value"

  - Type: "IIS"
    Filters:
        - "four"
        - "five"
    Settings:
        Param : "Value"