AppOptions:
    OutputFileName: "Bleh"
    AttachmentsDirectory: "TBD"
    MarkdownNotesFileName: ""
    InputFileNames:
        IagoStatisticsSet : "C:\\tmp\\parrot-server-stats.log"
        IISStatsSet : "TBD"
        AzurePerfStatsSet : "TBD"
    GraphType: "OxyPlot"

IagoStatistics:
    Filters:
        Name: "one"
        Asdf: "two"

IISStatistics:
    SubKey: "asdf"
    AppName: "asdf"